# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import frequencia.justificativas.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JustificativaFalta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.IntegerField(choices=[(0, 'Pendente'), (1, 'Indeferida'), (2, 'Deferida')], default=0, verbose_name='Status da justificativa')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('inicio', models.DateField(verbose_name='Data de início')),
                ('termino', models.DateField(verbose_name='Data de término')),
                ('comprovante', models.FileField(blank=True, upload_to='anexos_justificativas/', validators=[frequencia.justificativas.validators.validate_file_extension], verbose_name='Comprovante')),
                ('parecer', models.TextField(blank=True, verbose_name='Parecer da chefia')),
                ('horas_abonadas', models.DurationField(blank=True, null=True, verbose_name='Tempo abonado')),
            ],
            options={
                'verbose_name': 'Justificativa de falta',
                'verbose_name_plural': 'Justificativas de falta',
            },
        ),
        migrations.CreateModel(
            name='TipoJustificativaFalta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=100, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de justificativa',
                'verbose_name_plural': 'Tipos de justificativa',
            },
        ),
        migrations.AddField(
            model_name='justificativafalta',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificativas', to='justificativas.TipoJustificativaFalta', verbose_name='Tipo de justificativa'),
        ),
    ]
