# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justificativas', '0002_auto_20171024_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipojustificativafalta',
            name='comprovante_obrigatorio',
            field=models.BooleanField(default=False, verbose_name='Comprovante obrigatório'),
        ),
    ]
