# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justificativas', '0004_justificativafalta_usuario_analise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificativafalta',
            name='horas_abonadas',
            field=models.DurationField(blank=True, null=True, verbose_name='Tempo abonado'),
        ),
        migrations.AlterField(
            model_name='justificativafalta',
            name='parecer',
            field=models.TextField(blank=True, verbose_name='Parecer da chefia'),
        ),
    ]
