# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justificativas', '0005_auto_20170906_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='justificativafalta',
            name='comprovante',
            field=models.FileField(blank=True, upload_to='', verbose_name='Comprovante'),
        ),
    ]
