# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import frequencia.justificativas.validators


class Migration(migrations.Migration):

    dependencies = [
        ('justificativas', '0006_justificativafalta_comprovante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificativafalta',
            name='comprovante',
            field=models.FileField(blank=True, upload_to='anexos_justificativas/', validators=[frequencia.justificativas.validators.validate_file_extension], verbose_name='Comprovante'),
        ),
    ]
