# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 14:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('carga_horaria_diaria', models.IntegerField()),
                ('turno', models.IntegerField(choices=[(0, 'Matutino'), (1, 'Verpertino'), (2, 'Noturno')], default=0, verbose_name='Turno')),
            ],
            options={
                'verbose_name_plural': 'Bolsistas',
                'verbose_name': 'Bolsista',
            },
        ),
        migrations.CreateModel(
            name='Coordenadoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('coordenadores', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Coordenadorias',
                'verbose_name': 'Coordenadoria',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('chefes', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('coordenadoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setores', to='vinculos.Coordenadoria', verbose_name='Coordenadoria')),
            ],
            options={
                'verbose_name_plural': 'Setores',
                'verbose_name': 'Setor',
            },
        ),
        migrations.AddField(
            model_name='bolsista',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsistas', to='vinculos.Setor', verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='bolsista',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsistas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
