# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculo',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Vínculo ativo'),
        ),
        migrations.AlterField(
            model_name='vinculo',
            name='carga_horaria_diaria',
            field=models.IntegerField(blank=True, null=True, verbose_name='Carga horária diária'),
        ),
        migrations.AlterField(
            model_name='vinculo',
            name='turno',
            field=models.IntegerField(choices=[('', ''), (0, 'Matutino'), (1, 'Verpertino'), (2, 'Noturno')], default='', verbose_name='Turno'),
        ),
    ]
