# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenadoria',
            name='coordenadores',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
