# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinculos', '0002_auto_20170802_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolsista',
            name='vinculo_ativado',
            field=models.BooleanField(default=True),
        ),
    ]
