# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinculos', '0004_auto_20170830_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculo',
            name='turno',
            field=models.IntegerField(blank=True, choices=[(None, ''), (0, 'Matutino'), (1, 'Verpertino'), (2, 'Noturno')], null=True, verbose_name='Turno'),
        ),
    ]
