# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 22:04
from __future__ import unicode_literals

from django.db import migrations
import frequencia.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', frequencia.accounts.models.CustomUserManager()),
            ],
        ),
    ]
