# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justificativas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='justificativafalta',
            name='horas_abonadas',
            field=models.TimeField(blank=True, null=True, verbose_name='Horas abonadas'),
        ),
        migrations.AddField(
            model_name='justificativafalta',
            name='parecer',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
    ]
