# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justificativas', '0002_auto_20170831_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificativafalta',
            name='horas_abonadas',
            field=models.DurationField(blank=True, null=True, verbose_name='Horas abonadas'),
        ),
    ]
