# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vinculos', '0005_auto_20170830_1153'),
        ('justificativas', '0003_auto_20170831_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='justificativafalta',
            name='usuario_analise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='justificativas_homologadas', to='vinculos.Vinculo', verbose_name='Analisado por'),
        ),
    ]
