# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinculos', '0002_auto_20170824_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculo',
            name='turno',
            field=models.IntegerField(blank=True, choices=[(0, 'Matutino'), (1, 'Verpertino'), (2, 'Noturno')], verbose_name='Turno'),
        ),
    ]
