# Generated by Django 3.2.14 on 2022-08-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20171024_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
