# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feriadocalendarioacademico',
            options={'verbose_name': 'Feriado', 'verbose_name_plural': 'Feriados'},
        ),
    ]
