# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vinculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('tipo', models.IntegerField(choices=[(0, 'Entrada'), (1, 'Saída')], default=0, verbose_name='Tipo')),
                ('bolsista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='vinculos.Bolsista', verbose_name='Bolsista')),
            ],
            options={
                'verbose_name_plural': 'Frequências',
                'verbose_name': 'Frequência',
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('descricao', models.CharField(blank=True, max_length=100, verbose_name='Descricao')),
                ('ip', models.GenericIPAddressField(unique=True, unpack_ipv4=True, verbose_name='Endereço IP')),
            ],
            options={
                'verbose_name_plural': 'Máquinas',
                'verbose_name': 'Máquina',
            },
        ),
        migrations.AddField(
            model_name='frequencia',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='registro.Maquina', verbose_name='Máquina'),
        ),
    ]
