# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='ip',
            field=models.GenericIPAddressField(unique=True, unpack_ipv4=True, verbose_name='Endereço IP'),
        ),
    ]
