# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20170804_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='bolsista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='vinculos.Vinculo', verbose_name='Bolsista'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='registro.Maquina', verbose_name='Máquina'),
        ),
    ]
